name: seai
channels:
  - pytorch
  - ultralytics
  - conda-forge
  - defaults
dependencies:
  - python=3.9  # Or your desired python version
  - matplotlib==3.5.1
  - numpy==1.21.5
  - pandas==1.4.2
  - scipy==1.7.3
  - seaborn==0.11.2
  - streamlit==1.11.1
  - pytorch==1.13.1
  - pip
  - pip:
      - opencv-python==4.7.0.72
      - pycaret==3.0.0
      - ultralytics==8.0.47
      - xgboost==1.7.5
